"""
install_autostart.py — one-shot installer for NOVA's boot auto-start.

Generates a VBS launcher (windowless pythonw, NOVA_AUTOSTART=1) and drops
a copy into the current user's Startup folder, so every Windows login:

  - NOVA starts hidden (no console window)
  - Ollama is brought up automatically if it isn't running
  - NOVA greets: "Welcome back sir how can I assist you today"
  - the NOVA UI opens in the browser (OPEN_UI_ON_BOOT)

Run:  python install_autostart.py           (install / update)
      python install_autostart.py remove    (uninstall)
      python install_autostart.py status    (check)
"""

import os
import shutil
import sys

import config

STARTUP = os.path.join(
    os.environ.get("APPDATA", os.path.expanduser("~")),
    "Microsoft", "Windows", "Start Menu", "Programs", "Startup",
)
VBS_NAME = "nova_autostart.vbs"

TEMPLATE = """\
' ============================================================
' NOVA auto-start launcher - generated by install_autostart.py
' Starts NOVA hidden on Windows login with NOVA_AUTOSTART=1,
' so NOVA greets you and the UI opens automatically.
' ============================================================
Option Explicit
Dim shell, novaDir, pythonw, cmd
Set shell = CreateObject("WScript.Shell")
novaDir = "__NOVA_DIR__"
pythonw = "__PYTHONW__"
shell.CurrentDirectory = novaDir
shell.Environment("PROCESS")("NOVA_AUTOSTART") = "1"
cmd = Chr(34) & pythonw & Chr(34) & " " & Chr(34) & novaDir & "\\main.py" & Chr(34)
shell.Run cmd, 0, False
"""


def _pythonw() -> str:
    """pythonw.exe = same interpreter, no console window."""
    exe = sys.executable
    candidate = os.path.join(os.path.dirname(exe), "pythonw.exe")
    return candidate if os.path.exists(candidate) else exe


def _render() -> str:
    return TEMPLATE.replace("__NOVA_DIR__", config.BASE_DIR).replace(
        "__PYTHONW__", _pythonw()
    )


def install():
    if not config.AUTO_START_ON_BOOT:
        print("AUTO_START_ON_BOOT is False in config.py - not installing.")
        return
    os.makedirs(STARTUP, exist_ok=True)

    project_copy = os.path.join(config.BASE_DIR, VBS_NAME)
    with open(project_copy, "w", encoding="utf-8") as f:
        f.write(_render())

    startup_copy = os.path.join(STARTUP, VBS_NAME)
    shutil.copyfile(project_copy, startup_copy)

    print("NOVA auto-start installed.")
    print(f"  launcher : {startup_copy}")
    print(f"  pythonw  : {_pythonw()}")
    _install_hotkey_shortcut()
    print("NOVA will start hidden on every login and greet you, sir.")


def _install_hotkey_shortcut():
    """
    Desktop shortcut carrying the native Ctrl+J hotkey. This covers the
    cold case: pressing Ctrl+J while NOVA is NOT running boots it. While
    NOVA IS running, its own global hotkey (core/hotkey.py) opens the UI
    and the extra launch exits via the duplicate-instance guard.
    """
    try:
        import win32com.client

        shell = win32com.client.Dispatch("WScript.Shell")
        desktop = shell.SpecialFolders("Desktop")
        lnk_path = os.path.join(desktop, "NOVA.lnk")
        shortcut = shell.CreateShortCut(lnk_path)
        shortcut.TargetPath = os.path.join(config.BASE_DIR, VBS_NAME)
        shortcut.WorkingDirectory = config.BASE_DIR
        shortcut.Description = "Start NOVA (Ctrl+J)"
        shortcut.Hotkey = "Ctrl+J"
        shortcut.Save()
        print(f"  hotkey   : Ctrl+J -> {lnk_path}")
    except Exception as e:
        print(f"  hotkey shortcut skipped: {e}")


def remove():
    startup_copy = os.path.join(STARTUP, VBS_NAME)
    if os.path.exists(startup_copy):
        os.remove(startup_copy)
        print("Removed:", startup_copy)
    else:
        print("Nothing to remove - auto-start was not installed.")


def status():
    startup_copy = os.path.join(STARTUP, VBS_NAME)
    installed = os.path.exists(startup_copy)
    print(f"installed: {installed}  ({startup_copy})")
    if installed:
        print(f"greeting on boot: {config.BOOT_GREETING!r}")


if __name__ == "__main__":
    mode = (sys.argv[1] if len(sys.argv) > 1 else "install").lower()
    {"install": install, "remove": remove, "status": status}.get(mode, install)()
