' ============================================================
' NOVA auto-start launcher - generated by install_autostart.py
' Starts NOVA hidden on Windows login with NOVA_AUTOSTART=1,
' so NOVA greets you and the UI opens automatically.
' ============================================================
Option Explicit
Dim shell, novaDir, pythonw, cmd
Set shell = CreateObject("WScript.Shell")
novaDir = "C:\Users\Personal\Music\NOVA"
pythonw = "C:\Users\Personal\AppData\Local\Programs\Python\Python313\pythonw.exe"
shell.CurrentDirectory = novaDir
shell.Environment("PROCESS")("NOVA_AUTOSTART") = "1"
cmd = Chr(34) & pythonw & Chr(34) & " " & Chr(34) & novaDir & "\main.py" & Chr(34)
shell.Run cmd, 0, False
